confition for input validtion for utility method
SerhiiYahdzhyiev/tabs-manager pull request #70
Opened 2024-10-21 03:21 UTC by SandipGyawali

2024-10-21 03:23 UTC, SandipGyawali commented
@SerhiiYahdzhyiev #68

2024-10-21 09:35 UTC, SerhiiYahdzhyiev commented on src/utils.ts
> +
I would prefer the error message to be: "Invalid input: " + url.

Also please extend the condition check with: `typeof url !== "string"`.

2024-10-21 09:38 UTC, SerhiiYahdzhyiev commented
Also please format your commit message. For reference check [this](https://gist.github.com/finalfantasia/bd0070673ca27e5f7473).

Also don't forget to run `lint` and `format` scripts before pushing. Maybe in future I will add corresponding git hooks to the repo directly.

2024-10-21 13:50 UTC, SandipGyawali commented
@SerhiiYahdzhyiev okay

2024-10-27 09:01 UTC, SandipGyawali commented
> Also please format your commit message. For reference check [this](https://gist.github.com/finalfantasia/bd0070673ca27e5f7473).
> 
> Also don't forget to run `lint` and `format` scripts before pushing. Maybe in future I will add corresponding git hooks to the repo directly.

updated as you mentioned on the folllowing lines.

2024-10-30 10:34 UTC, SerhiiYahdzhyiev requested changes

2024-10-30 10:35 UTC, SerhiiYahdzhyiev commented on src/utils.ts
> +  if (typeof url == "string" && !url.trim())
If you are serious about the contributions, take time to read the corresponding sections in README and CONTRIBUTING docs.

2024-11-06 07:55 UTC, SerhiiYahdzhyiev commented
Closing as not yet relevant.

2024-11-06 07:55 UTC, closed without merging